### ISSUE TITLE
The odometry folder is not refactored and not according to required format

### ISSUE THREAD

**Issue by aniket0112** [DRISHTI-SVNIT/Tiva-Libraries#4]
Please convert the odometry folder in a header and source code format rather than a project @animeshpanara

**Comment by animeshpanara** [comment]
ok sir

**Comment by animeshpanara** [comment]
sir already ek library hai just odometry pe wo apllication wala hai

**Comment by aniket0112** [comment]
Ok I see it. I will remove the extra files then. Closing the issue.

**Comment by animeshpanara** [comment]
odometry project with main1 and different libraries for odometry
https://drive.google.com/open?id=0B9cxajjgs0qgeURVZGNSZjh0WTg
check this out compiled also
